// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRz_q1ignV2iJHTY1bDy6vhE7G5ICkTQ',
    appId: '1:18483164142:web:f965776b4239a1f97894ff',
    messagingSenderId: '18483164142',
    projectId: 'quiz-for-children-f268b',
    authDomain: 'quiz-for-children-f268b.firebaseapp.com',
    storageBucket: 'quiz-for-children-f268b.appspot.com',
    measurementId: 'G-SH3G5PHC3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg3KADlY7RsUBTzPXivSiWuOhSjDd4zNs',
    appId: '1:18483164142:android:3b882b682300d5737894ff',
    messagingSenderId: '18483164142',
    projectId: 'quiz-for-children-f268b',
    storageBucket: 'quiz-for-children-f268b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlQER2ZZbOmKRQNiAEqf0Stugha893bg',
    appId: '1:18483164142:ios:0392216eea5018027894ff',
    messagingSenderId: '18483164142',
    projectId: 'quiz-for-children-f268b',
    storageBucket: 'quiz-for-children-f268b.appspot.com',
    iosBundleId: 'com.example.childQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAlQER2ZZbOmKRQNiAEqf0Stugha893bg',
    appId: '1:18483164142:ios:0392216eea5018027894ff',
    messagingSenderId: '18483164142',
    projectId: 'quiz-for-children-f268b',
    storageBucket: 'quiz-for-children-f268b.appspot.com',
    iosBundleId: 'com.example.childQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjRz_q1ignV2iJHTY1bDy6vhE7G5ICkTQ',
    appId: '1:18483164142:web:1f98b3bdb9e2b1327894ff',
    messagingSenderId: '18483164142',
    projectId: 'quiz-for-children-f268b',
    authDomain: 'quiz-for-children-f268b.firebaseapp.com',
    storageBucket: 'quiz-for-children-f268b.appspot.com',
    measurementId: 'G-459PD7WFTS',
  );
}
